add unit tests and test with mocks
OlegChub/JavaUnitTesting pull request #1
Opened 2022-11-07 08:51 UTC by OlegChub

2022-11-07 10:16 UTC, dsalonka approved these changes

2022-11-07 13:41 UTC, Fentezi3 approved these changes
I'm not sure, what empty line inside the test method it's a good idea, but ok.
And maybe "inIt" in the and of methods name is not necessary (e.a.  getCartTotalPriceWithOneProductWithoutParams**InIt**) but it's not critical for me too.

2022-11-10 15:01 UTC, dKatechev requested changes

2022-11-10 15:01 UTC, dKatechev commented on src/test/java/ShoppingCartTest.java
> +
why so much empty lines?

2022-11-10 15:01 UTC, dKatechev commented on src/test/java/ShoppingCartTest.java
> +        assertEquals(PRODUCT2, shoppingCart.getProductById(2));
You created special constant for this: PRODUCT2_ID

2022-11-10 15:01 UTC, dKatechev commented on src/test/java/ShoppingCartTest.java
> +        assertThrows(ProductNotFoundException.class, () -> shoppingCart.getProductById(1));
You created special constant for this: PRODUCT1_ID

2022-11-10 15:01 UTC, dKatechev commented on src/test/java/ShoppingCartTest.java
> +        assertEquals(0, productsList.size());
Why do you check **productsList** size instead of **shoppingCard products** size?
Here and in each other test.

2022-11-10 15:01 UTC, dKatechev commented on src/test/java/ShoppingCartTest.java
> +
How about to test adding of the same product more than once? This functionality have dedicated logic, but not covered right now.

2022-11-10 15:20 UTC, OlegChub commented on src/test/java/ShoppingCartTest.java
> +
I thought it would be more readable. Removed empty lines

2022-11-10 15:21 UTC, OlegChub commented on src/test/java/ShoppingCartTest.java
> +        assertEquals(PRODUCT2, shoppingCart.getProductById(2));
Missed this moment. Corrected

2022-11-10 15:21 UTC, OlegChub commented on src/test/java/ShoppingCartTest.java
> +        assertThrows(ProductNotFoundException.class, () -> shoppingCart.getProductById(1));
Missed this moment. Corrected

2022-11-10 15:22 UTC, OlegChub commented on src/test/java/ShoppingCartTest.java
> +        assertEquals(0, productsList.size());
Replaced by shoppingCart.getProducts().size()

2022-11-10 15:30 UTC, OlegChub commented on src/test/java/ShoppingCartTest.java
> +
add one more test

2022-11-11 05:48 UTC, dKatechev approved these changes

2022-11-14 09:56 UTC, merged